# This file has been generated by node2nix 1.11.1. Do not edit!

{
  pkgs ? import <nixpkgs> {
    inherit system;
  },
  system ? builtins.currentSystem,
  nodejs ? pkgs."nodejs_14",
}:

let
  nodeEnv = pkgs.callPackage ./node-env.nix {
    inherit nodejs;
    libtool = if pkgs.stdenv.isDarwin then pkgs.cctools or pkgs.darwin.cctools else null;
  };
in
pkgs.callPackage ./node-packages.nix {
  inherit nodeEnv;
}
